-- ============================================================================
-- DEPRECATED / DO NOT RUN
-- ============================================================================
-- This file used to contain a hand-written partial schema plus a seeded
-- default admin account (admin/admin123). It was NOT used by any code path,
-- and its schema had diverged from the canonical migrations (e.g. it declared
-- post_type/post_status ENUMs and a `site_id` column that the real schema does
-- not use). Running it against a real database produces an inconsistent schema
-- and a known-credential admin user — a security risk.
--
-- It has been intentionally emptied to remove that footgun.
--
-- To initialize a RustPress database, use the migration tool, which applies the
-- canonical SQL files in `migrations/` and tracks them in `schema_migrations`:
--
--     cargo run --bin rustpress-migrate           # or: rustpress-migrate
--
-- The first administrator account is created through the application setup
-- flow (see crates/rustpress-server/src/setup.rs), not by seeding SQL.
-- ============================================================================
