import { create } from 'zustand';
import { persist } from 'zustand/middleware';

// Table Style Definition
export interface TableStyleConfig {
  // Basic Info
  id: string;
  name: string;
  category: TableStyleCategory;
  description: string;
  isCustom: boolean;

  // Header Styles
  header: {
    backgroundColor: string;
    textColor: string;
    fontWeight: 'normal' | 'medium' | 'semibold' | 'bold';
    fontSize: 'xs' | 'sm' | 'base' | 'lg';
    textTransform: 'none' | 'uppercase' | 'lowercase' | 'capitalize';
    borderBottom: string;
    padding: string;
  };

  // Body Styles
  body: {
    backgroundColor: string;
    alternateRowColor: string;
    textColor: string;
    fontSize: 'xs' | 'sm' | 'base' | 'lg';
    padding: string;
  };

  // Border Styles
  border: {
    style: 'none' | 'solid' | 'dashed' | 'dotted';
    width: string;
    color: string;
    radius: string;
    cellBorders: boolean;
    headerBorder: boolean;
  };

  // Effects
  effects: {
    striped: boolean;
    hoverable: boolean;
    hoverColor: string;
    shadow: 'none' | 'sm' | 'md' | 'lg' | 'xl';
    animation: 'none' | 'fade' | 'slide' | 'scale';
  };

  // Footer Styles (optional)
  footer?: {
    backgroundColor: string;
    textColor: string;
    fontWeight: 'normal' | 'medium' | 'semibold' | 'bold';
    borderTop: string;
  };
}

export type TableStyleCategory =
  | 'minimal'
  | 'modern'
  | 'classic'
  | 'colorful'
  | 'professional'
  | 'creative'
  | 'dark'
  | 'gradient'
  | 'custom'
  | 'theme';

// 50 Predefined Table Styles
export const defaultTableStyles: TableStyleConfig[] = [
  // Theme Default
  {
    id: 'theme-default',
    name: 'Theme Default',
    category: 'theme',
    description: 'Uses your current theme colors',
    isCustom: false,
    header: {
      backgroundColor: 'var(--primary-100)',
      textColor: 'var(--primary-900)',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '2px solid var(--primary-500)',
      padding: '12px 16px',
    },
    body: {
      backgroundColor: 'var(--background)',
      alternateRowColor: 'var(--muted)',
      textColor: 'var(--foreground)',
      fontSize: 'sm',
      padding: '10px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: 'var(--border)',
      radius: '8px',
      cellBorders: true,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: 'var(--accent)',
      shadow: 'sm',
      animation: 'fade',
    },
  },

  // MINIMAL STYLES (1-8)
  {
    id: 'minimal-clean',
    name: 'Clean Minimal',
    category: 'minimal',
    description: 'Simple and clean with no borders',
    isCustom: false,
    header: {
      backgroundColor: 'transparent',
      textColor: '#374151',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'uppercase',
      borderBottom: '1px solid #e5e7eb',
      padding: '8px 12px',
    },
    body: {
      backgroundColor: 'transparent',
      alternateRowColor: 'transparent',
      textColor: '#4b5563',
      fontSize: 'sm',
      padding: '8px 12px',
    },
    border: {
      style: 'none',
      width: '0',
      color: 'transparent',
      radius: '0',
      cellBorders: false,
      headerBorder: true,
    },
    effects: {
      striped: false,
      hoverable: true,
      hoverColor: '#f9fafb',
      shadow: 'none',
      animation: 'none',
    },
  },
  {
    id: 'minimal-lines',
    name: 'Horizontal Lines',
    category: 'minimal',
    description: 'Clean horizontal dividers',
    isCustom: false,
    header: {
      backgroundColor: 'transparent',
      textColor: '#111827',
      fontWeight: 'medium',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '2px solid #111827',
      padding: '12px 8px',
    },
    body: {
      backgroundColor: 'transparent',
      alternateRowColor: 'transparent',
      textColor: '#374151',
      fontSize: 'sm',
      padding: '12px 8px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#e5e7eb',
      radius: '0',
      cellBorders: false,
      headerBorder: true,
    },
    effects: {
      striped: false,
      hoverable: true,
      hoverColor: '#f3f4f6',
      shadow: 'none',
      animation: 'none',
    },
  },
  {
    id: 'minimal-dots',
    name: 'Dotted Borders',
    category: 'minimal',
    description: 'Subtle dotted cell borders',
    isCustom: false,
    header: {
      backgroundColor: '#fafafa',
      textColor: '#374151',
      fontWeight: 'medium',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '1px dotted #d1d5db',
      padding: '10px 12px',
    },
    body: {
      backgroundColor: 'transparent',
      alternateRowColor: 'transparent',
      textColor: '#4b5563',
      fontSize: 'sm',
      padding: '10px 12px',
    },
    border: {
      style: 'dotted',
      width: '1px',
      color: '#e5e7eb',
      radius: '4px',
      cellBorders: true,
      headerBorder: true,
    },
    effects: {
      striped: false,
      hoverable: true,
      hoverColor: '#f9fafb',
      shadow: 'none',
      animation: 'none',
    },
  },
  {
    id: 'minimal-ghost',
    name: 'Ghost Table',
    category: 'minimal',
    description: 'Nearly invisible structure',
    isCustom: false,
    header: {
      backgroundColor: 'transparent',
      textColor: '#6b7280',
      fontWeight: 'normal',
      fontSize: 'xs',
      textTransform: 'uppercase',
      borderBottom: '1px solid #f3f4f6',
      padding: '6px 10px',
    },
    body: {
      backgroundColor: 'transparent',
      alternateRowColor: 'transparent',
      textColor: '#374151',
      fontSize: 'sm',
      padding: '8px 10px',
    },
    border: {
      style: 'none',
      width: '0',
      color: 'transparent',
      radius: '0',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: false,
      hoverable: true,
      hoverColor: '#f9fafb',
      shadow: 'none',
      animation: 'fade',
    },
  },
  {
    id: 'minimal-compact',
    name: 'Compact',
    category: 'minimal',
    description: 'Dense layout for data-heavy tables',
    isCustom: false,
    header: {
      backgroundColor: '#f9fafb',
      textColor: '#111827',
      fontWeight: 'medium',
      fontSize: 'xs',
      textTransform: 'none',
      borderBottom: '1px solid #e5e7eb',
      padding: '4px 8px',
    },
    body: {
      backgroundColor: 'transparent',
      alternateRowColor: '#fafafa',
      textColor: '#374151',
      fontSize: 'xs',
      padding: '4px 8px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#f3f4f6',
      radius: '2px',
      cellBorders: true,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#f3f4f6',
      shadow: 'none',
      animation: 'none',
    },
  },
  {
    id: 'minimal-spacious',
    name: 'Spacious',
    category: 'minimal',
    description: 'Extra breathing room',
    isCustom: false,
    header: {
      backgroundColor: 'transparent',
      textColor: '#374151',
      fontWeight: 'semibold',
      fontSize: 'base',
      textTransform: 'none',
      borderBottom: '1px solid #e5e7eb',
      padding: '16px 20px',
    },
    body: {
      backgroundColor: 'transparent',
      alternateRowColor: 'transparent',
      textColor: '#4b5563',
      fontSize: 'base',
      padding: '16px 20px',
    },
    border: {
      style: 'none',
      width: '0',
      color: 'transparent',
      radius: '0',
      cellBorders: false,
      headerBorder: true,
    },
    effects: {
      striped: false,
      hoverable: true,
      hoverColor: '#f9fafb',
      shadow: 'none',
      animation: 'fade',
    },
  },
  {
    id: 'minimal-underline',
    name: 'Underlined Rows',
    category: 'minimal',
    description: 'Simple underlined rows',
    isCustom: false,
    header: {
      backgroundColor: 'transparent',
      textColor: '#111827',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '2px solid #374151',
      padding: '10px 12px',
    },
    body: {
      backgroundColor: 'transparent',
      alternateRowColor: 'transparent',
      textColor: '#374151',
      fontSize: 'sm',
      padding: '10px 12px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#e5e7eb',
      radius: '0',
      cellBorders: false,
      headerBorder: true,
    },
    effects: {
      striped: false,
      hoverable: true,
      hoverColor: '#fafafa',
      shadow: 'none',
      animation: 'none',
    },
  },
  {
    id: 'minimal-elegant',
    name: 'Elegant',
    category: 'minimal',
    description: 'Refined and sophisticated',
    isCustom: false,
    header: {
      backgroundColor: 'transparent',
      textColor: '#1f2937',
      fontWeight: 'medium',
      fontSize: 'sm',
      textTransform: 'capitalize',
      borderBottom: '1px solid #d1d5db',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: 'transparent',
      alternateRowColor: 'transparent',
      textColor: '#4b5563',
      fontSize: 'sm',
      padding: '14px 16px',
    },
    border: {
      style: 'none',
      width: '0',
      color: 'transparent',
      radius: '0',
      cellBorders: false,
      headerBorder: true,
    },
    effects: {
      striped: false,
      hoverable: true,
      hoverColor: '#f9fafb',
      shadow: 'none',
      animation: 'fade',
    },
  },

  // MODERN STYLES (9-16)
  {
    id: 'modern-rounded',
    name: 'Modern Rounded',
    category: 'modern',
    description: 'Soft rounded corners with shadow',
    isCustom: false,
    header: {
      backgroundColor: '#f8fafc',
      textColor: '#1e293b',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#f8fafc',
      textColor: '#334155',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#e2e8f0',
      radius: '12px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#f1f5f9',
      shadow: 'md',
      animation: 'fade',
    },
  },
  {
    id: 'modern-card',
    name: 'Card Style',
    category: 'modern',
    description: 'Each row as a card',
    isCustom: false,
    header: {
      backgroundColor: 'transparent',
      textColor: '#64748b',
      fontWeight: 'medium',
      fontSize: 'xs',
      textTransform: 'uppercase',
      borderBottom: 'none',
      padding: '8px 16px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#ffffff',
      textColor: '#1e293b',
      fontSize: 'sm',
      padding: '16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#e2e8f0',
      radius: '8px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: false,
      hoverable: true,
      hoverColor: '#f8fafc',
      shadow: 'sm',
      animation: 'scale',
    },
  },
  {
    id: 'modern-glass',
    name: 'Glassmorphism',
    category: 'modern',
    description: 'Frosted glass effect',
    isCustom: false,
    header: {
      backgroundColor: 'rgba(255, 255, 255, 0.7)',
      textColor: '#1e293b',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '1px solid rgba(255, 255, 255, 0.5)',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: 'rgba(255, 255, 255, 0.5)',
      alternateRowColor: 'rgba(255, 255, 255, 0.3)',
      textColor: '#334155',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: 'rgba(255, 255, 255, 0.5)',
      radius: '16px',
      cellBorders: false,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: 'rgba(255, 255, 255, 0.8)',
      shadow: 'lg',
      animation: 'fade',
    },
  },
  {
    id: 'modern-flat',
    name: 'Flat Design',
    category: 'modern',
    description: 'Bold flat colors',
    isCustom: false,
    header: {
      backgroundColor: '#3b82f6',
      textColor: '#ffffff',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#eff6ff',
      textColor: '#1e40af',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'none',
      width: '0',
      color: 'transparent',
      radius: '8px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#dbeafe',
      shadow: 'sm',
      animation: 'none',
    },
  },
  {
    id: 'modern-neumorphic',
    name: 'Neumorphic',
    category: 'modern',
    description: 'Soft UI with depth',
    isCustom: false,
    header: {
      backgroundColor: '#e0e5ec',
      textColor: '#374151',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '16px',
    },
    body: {
      backgroundColor: '#e0e5ec',
      alternateRowColor: '#e0e5ec',
      textColor: '#4b5563',
      fontSize: 'sm',
      padding: '14px 16px',
    },
    border: {
      style: 'none',
      width: '0',
      color: 'transparent',
      radius: '16px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: false,
      hoverable: true,
      hoverColor: '#d1d5db',
      shadow: 'lg',
      animation: 'scale',
    },
  },
  {
    id: 'modern-outline',
    name: 'Outlined',
    category: 'modern',
    description: 'Clean outlined cells',
    isCustom: false,
    header: {
      backgroundColor: 'transparent',
      textColor: '#3b82f6',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '2px solid #3b82f6',
      padding: '12px 16px',
    },
    body: {
      backgroundColor: 'transparent',
      alternateRowColor: 'transparent',
      textColor: '#374151',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '2px',
      color: '#3b82f6',
      radius: '8px',
      cellBorders: true,
      headerBorder: true,
    },
    effects: {
      striped: false,
      hoverable: true,
      hoverColor: '#eff6ff',
      shadow: 'none',
      animation: 'fade',
    },
  },
  {
    id: 'modern-neon',
    name: 'Neon Glow',
    category: 'modern',
    description: 'Glowing neon borders',
    isCustom: false,
    header: {
      backgroundColor: '#0f172a',
      textColor: '#22d3ee',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'uppercase',
      borderBottom: '1px solid #22d3ee',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: '#0f172a',
      alternateRowColor: '#1e293b',
      textColor: '#e2e8f0',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#22d3ee',
      radius: '8px',
      cellBorders: true,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#164e63',
      shadow: 'lg',
      animation: 'fade',
    },
  },
  {
    id: 'modern-gradient-border',
    name: 'Gradient Border',
    category: 'modern',
    description: 'Colorful gradient outline',
    isCustom: false,
    header: {
      backgroundColor: '#ffffff',
      textColor: '#7c3aed',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '1px solid #e5e7eb',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#faf5ff',
      textColor: '#374151',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '2px',
      color: '#8b5cf6',
      radius: '12px',
      cellBorders: false,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#f3e8ff',
      shadow: 'md',
      animation: 'fade',
    },
  },

  // CLASSIC STYLES (17-24)
  {
    id: 'classic-traditional',
    name: 'Traditional',
    category: 'classic',
    description: 'Classic bordered table',
    isCustom: false,
    header: {
      backgroundColor: '#1f2937',
      textColor: '#ffffff',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '2px solid #1f2937',
      padding: '12px 16px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#f3f4f6',
      textColor: '#1f2937',
      fontSize: 'sm',
      padding: '10px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#d1d5db',
      radius: '0',
      cellBorders: true,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#e5e7eb',
      shadow: 'none',
      animation: 'none',
    },
  },
  {
    id: 'classic-excel',
    name: 'Excel Style',
    category: 'classic',
    description: 'Spreadsheet look',
    isCustom: false,
    header: {
      backgroundColor: '#f0f0f0',
      textColor: '#000000',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '1px solid #999999',
      padding: '4px 8px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#ffffff',
      textColor: '#000000',
      fontSize: 'sm',
      padding: '4px 8px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#cccccc',
      radius: '0',
      cellBorders: true,
      headerBorder: true,
    },
    effects: {
      striped: false,
      hoverable: true,
      hoverColor: '#d4edda',
      shadow: 'none',
      animation: 'none',
    },
  },
  {
    id: 'classic-newspaper',
    name: 'Newspaper',
    category: 'classic',
    description: 'Editorial style',
    isCustom: false,
    header: {
      backgroundColor: 'transparent',
      textColor: '#000000',
      fontWeight: 'bold',
      fontSize: 'base',
      textTransform: 'none',
      borderBottom: '3px double #000000',
      padding: '8px 12px',
    },
    body: {
      backgroundColor: 'transparent',
      alternateRowColor: 'transparent',
      textColor: '#1a1a1a',
      fontSize: 'sm',
      padding: '8px 12px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#cccccc',
      radius: '0',
      cellBorders: false,
      headerBorder: true,
    },
    effects: {
      striped: false,
      hoverable: false,
      hoverColor: 'transparent',
      shadow: 'none',
      animation: 'none',
    },
  },
  {
    id: 'classic-ledger',
    name: 'Ledger',
    category: 'classic',
    description: 'Accounting ledger style',
    isCustom: false,
    header: {
      backgroundColor: '#fef3c7',
      textColor: '#78350f',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '2px solid #d97706',
      padding: '10px 14px',
    },
    body: {
      backgroundColor: '#fffbeb',
      alternateRowColor: '#fef3c7',
      textColor: '#451a03',
      fontSize: 'sm',
      padding: '8px 14px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#fcd34d',
      radius: '0',
      cellBorders: true,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#fde68a',
      shadow: 'none',
      animation: 'none',
    },
  },
  {
    id: 'classic-blueprint',
    name: 'Blueprint',
    category: 'classic',
    description: 'Technical drawing style',
    isCustom: false,
    header: {
      backgroundColor: '#1e3a5f',
      textColor: '#ffffff',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'uppercase',
      borderBottom: '2px solid #60a5fa',
      padding: '12px 16px',
    },
    body: {
      backgroundColor: '#0f172a',
      alternateRowColor: '#1e293b',
      textColor: '#93c5fd',
      fontSize: 'sm',
      padding: '10px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#3b82f6',
      radius: '0',
      cellBorders: true,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#1e40af',
      shadow: 'none',
      animation: 'none',
    },
  },
  {
    id: 'classic-vintage',
    name: 'Vintage',
    category: 'classic',
    description: 'Retro sepia tones',
    isCustom: false,
    header: {
      backgroundColor: '#451a03',
      textColor: '#fef3c7',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '2px solid #78350f',
      padding: '10px 14px',
    },
    body: {
      backgroundColor: '#fefce8',
      alternateRowColor: '#fef9c3',
      textColor: '#422006',
      fontSize: 'sm',
      padding: '8px 14px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#a16207',
      radius: '0',
      cellBorders: true,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#fef08a',
      shadow: 'sm',
      animation: 'none',
    },
  },
  {
    id: 'classic-academic',
    name: 'Academic',
    category: 'classic',
    description: 'Formal research paper style',
    isCustom: false,
    header: {
      backgroundColor: '#f5f5f5',
      textColor: '#1a1a1a',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '1px solid #1a1a1a',
      padding: '8px 10px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#ffffff',
      textColor: '#333333',
      fontSize: 'sm',
      padding: '6px 10px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#1a1a1a',
      radius: '0',
      cellBorders: false,
      headerBorder: true,
    },
    effects: {
      striped: false,
      hoverable: false,
      hoverColor: 'transparent',
      shadow: 'none',
      animation: 'none',
    },
  },
  {
    id: 'classic-invoice',
    name: 'Invoice',
    category: 'classic',
    description: 'Professional invoice style',
    isCustom: false,
    header: {
      backgroundColor: '#374151',
      textColor: '#f9fafb',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'uppercase',
      borderBottom: 'none',
      padding: '10px 16px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#f9fafb',
      textColor: '#1f2937',
      fontSize: 'sm',
      padding: '10px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#e5e7eb',
      radius: '4px',
      cellBorders: true,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#f3f4f6',
      shadow: 'sm',
      animation: 'none',
    },
    footer: {
      backgroundColor: '#f3f4f6',
      textColor: '#1f2937',
      fontWeight: 'bold',
      borderTop: '2px solid #374151',
    },
  },

  // COLORFUL STYLES (25-32)
  {
    id: 'colorful-rainbow',
    name: 'Rainbow',
    category: 'colorful',
    description: 'Colorful row gradients',
    isCustom: false,
    header: {
      backgroundColor: '#ec4899',
      textColor: '#ffffff',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '12px 16px',
    },
    body: {
      backgroundColor: '#fdf2f8',
      alternateRowColor: '#fce7f3',
      textColor: '#831843',
      fontSize: 'sm',
      padding: '10px 16px',
    },
    border: {
      style: 'none',
      width: '0',
      color: 'transparent',
      radius: '12px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#fbcfe8',
      shadow: 'md',
      animation: 'fade',
    },
  },
  {
    id: 'colorful-ocean',
    name: 'Ocean Blue',
    category: 'colorful',
    description: 'Deep sea colors',
    isCustom: false,
    header: {
      backgroundColor: '#0891b2',
      textColor: '#ffffff',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: '#ecfeff',
      alternateRowColor: '#cffafe',
      textColor: '#164e63',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#67e8f9',
      radius: '8px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#a5f3fc',
      shadow: 'sm',
      animation: 'fade',
    },
  },
  {
    id: 'colorful-forest',
    name: 'Forest Green',
    category: 'colorful',
    description: 'Natural green tones',
    isCustom: false,
    header: {
      backgroundColor: '#166534',
      textColor: '#ffffff',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: '#f0fdf4',
      alternateRowColor: '#dcfce7',
      textColor: '#14532d',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#86efac',
      radius: '8px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#bbf7d0',
      shadow: 'sm',
      animation: 'fade',
    },
  },
  {
    id: 'colorful-sunset',
    name: 'Sunset',
    category: 'colorful',
    description: 'Warm orange tones',
    isCustom: false,
    header: {
      backgroundColor: '#ea580c',
      textColor: '#ffffff',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: '#fff7ed',
      alternateRowColor: '#ffedd5',
      textColor: '#7c2d12',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#fdba74',
      radius: '8px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#fed7aa',
      shadow: 'sm',
      animation: 'fade',
    },
  },
  {
    id: 'colorful-lavender',
    name: 'Lavender',
    category: 'colorful',
    description: 'Soft purple hues',
    isCustom: false,
    header: {
      backgroundColor: '#7c3aed',
      textColor: '#ffffff',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: '#f5f3ff',
      alternateRowColor: '#ede9fe',
      textColor: '#4c1d95',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#c4b5fd',
      radius: '8px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#ddd6fe',
      shadow: 'sm',
      animation: 'fade',
    },
  },
  {
    id: 'colorful-cherry',
    name: 'Cherry Red',
    category: 'colorful',
    description: 'Bold red accent',
    isCustom: false,
    header: {
      backgroundColor: '#dc2626',
      textColor: '#ffffff',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: '#fef2f2',
      alternateRowColor: '#fee2e2',
      textColor: '#7f1d1d',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#fca5a5',
      radius: '8px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#fecaca',
      shadow: 'sm',
      animation: 'fade',
    },
  },
  {
    id: 'colorful-mint',
    name: 'Mint Fresh',
    category: 'colorful',
    description: 'Cool mint colors',
    isCustom: false,
    header: {
      backgroundColor: '#10b981',
      textColor: '#ffffff',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: '#ecfdf5',
      alternateRowColor: '#d1fae5',
      textColor: '#064e3b',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#6ee7b7',
      radius: '8px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#a7f3d0',
      shadow: 'sm',
      animation: 'fade',
    },
  },
  {
    id: 'colorful-royal',
    name: 'Royal Blue',
    category: 'colorful',
    description: 'Deep royal blue',
    isCustom: false,
    header: {
      backgroundColor: '#2563eb',
      textColor: '#ffffff',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: '#eff6ff',
      alternateRowColor: '#dbeafe',
      textColor: '#1e3a8a',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#93c5fd',
      radius: '8px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#bfdbfe',
      shadow: 'sm',
      animation: 'fade',
    },
  },

  // PROFESSIONAL STYLES (33-40)
  {
    id: 'pro-executive',
    name: 'Executive',
    category: 'professional',
    description: 'Corporate boardroom style',
    isCustom: false,
    header: {
      backgroundColor: '#18181b',
      textColor: '#fafafa',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'uppercase',
      borderBottom: 'none',
      padding: '14px 20px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#fafafa',
      textColor: '#27272a',
      fontSize: 'sm',
      padding: '12px 20px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#e4e4e7',
      radius: '0',
      cellBorders: true,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#f4f4f5',
      shadow: 'lg',
      animation: 'none',
    },
  },
  {
    id: 'pro-dashboard',
    name: 'Dashboard',
    category: 'professional',
    description: 'Analytics dashboard style',
    isCustom: false,
    header: {
      backgroundColor: '#f8fafc',
      textColor: '#475569',
      fontWeight: 'medium',
      fontSize: 'xs',
      textTransform: 'uppercase',
      borderBottom: '1px solid #e2e8f0',
      padding: '10px 16px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#f8fafc',
      textColor: '#0f172a',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#e2e8f0',
      radius: '8px',
      cellBorders: false,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#f1f5f9',
      shadow: 'sm',
      animation: 'fade',
    },
  },
  {
    id: 'pro-financial',
    name: 'Financial Report',
    category: 'professional',
    description: 'Formal financial data',
    isCustom: false,
    header: {
      backgroundColor: '#1e3a5f',
      textColor: '#ffffff',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '2px solid #3b82f6',
      padding: '12px 16px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#f0f9ff',
      textColor: '#1e3a5f',
      fontSize: 'sm',
      padding: '10px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#bfdbfe',
      radius: '0',
      cellBorders: true,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#e0f2fe',
      shadow: 'none',
      animation: 'none',
    },
    footer: {
      backgroundColor: '#f0f9ff',
      textColor: '#1e3a5f',
      fontWeight: 'bold',
      borderTop: '2px solid #1e3a5f',
    },
  },
  {
    id: 'pro-saas',
    name: 'SaaS Pricing',
    category: 'professional',
    description: 'Feature comparison table',
    isCustom: false,
    header: {
      backgroundColor: 'transparent',
      textColor: '#0f172a',
      fontWeight: 'bold',
      fontSize: 'base',
      textTransform: 'none',
      borderBottom: '2px solid #e2e8f0',
      padding: '16px 20px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#f8fafc',
      textColor: '#475569',
      fontSize: 'sm',
      padding: '16px 20px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#e2e8f0',
      radius: '12px',
      cellBorders: false,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#f1f5f9',
      shadow: 'lg',
      animation: 'scale',
    },
  },
  {
    id: 'pro-legal',
    name: 'Legal Document',
    category: 'professional',
    description: 'Formal legal style',
    isCustom: false,
    header: {
      backgroundColor: '#f8f9fa',
      textColor: '#212529',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '2px solid #212529',
      padding: '10px 14px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#ffffff',
      textColor: '#212529',
      fontSize: 'sm',
      padding: '8px 14px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#dee2e6',
      radius: '0',
      cellBorders: true,
      headerBorder: true,
    },
    effects: {
      striped: false,
      hoverable: false,
      hoverColor: 'transparent',
      shadow: 'none',
      animation: 'none',
    },
  },
  {
    id: 'pro-medical',
    name: 'Medical Records',
    category: 'professional',
    description: 'Healthcare data style',
    isCustom: false,
    header: {
      backgroundColor: '#0d9488',
      textColor: '#ffffff',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '12px 16px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#f0fdfa',
      textColor: '#134e4a',
      fontSize: 'sm',
      padding: '10px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#99f6e4',
      radius: '6px',
      cellBorders: true,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#ccfbf1',
      shadow: 'sm',
      animation: 'none',
    },
  },
  {
    id: 'pro-tech',
    name: 'Tech Specs',
    category: 'professional',
    description: 'Technical specifications',
    isCustom: false,
    header: {
      backgroundColor: '#4f46e5',
      textColor: '#ffffff',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'uppercase',
      borderBottom: 'none',
      padding: '12px 16px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#eef2ff',
      textColor: '#312e81',
      fontSize: 'sm',
      padding: '10px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#c7d2fe',
      radius: '8px',
      cellBorders: true,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#e0e7ff',
      shadow: 'md',
      animation: 'fade',
    },
  },
  {
    id: 'pro-startup',
    name: 'Startup Modern',
    category: 'professional',
    description: 'Contemporary business style',
    isCustom: false,
    header: {
      backgroundColor: '#f97316',
      textColor: '#ffffff',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '14px 18px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#fff7ed',
      textColor: '#1c1917',
      fontSize: 'sm',
      padding: '12px 18px',
    },
    border: {
      style: 'none',
      width: '0',
      color: 'transparent',
      radius: '16px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#ffedd5',
      shadow: 'xl',
      animation: 'scale',
    },
  },

  // DARK STYLES (41-46)
  {
    id: 'dark-midnight',
    name: 'Midnight',
    category: 'dark',
    description: 'Deep dark theme',
    isCustom: false,
    header: {
      backgroundColor: '#0f0f0f',
      textColor: '#ffffff',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '1px solid #262626',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: '#171717',
      alternateRowColor: '#1f1f1f',
      textColor: '#e5e5e5',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#262626',
      radius: '8px',
      cellBorders: true,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#262626',
      shadow: 'lg',
      animation: 'fade',
    },
  },
  {
    id: 'dark-charcoal',
    name: 'Charcoal',
    category: 'dark',
    description: 'Warm dark gray',
    isCustom: false,
    header: {
      backgroundColor: '#27272a',
      textColor: '#fafafa',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '1px solid #3f3f46',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: '#18181b',
      alternateRowColor: '#27272a',
      textColor: '#d4d4d8',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#3f3f46',
      radius: '8px',
      cellBorders: false,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#3f3f46',
      shadow: 'md',
      animation: 'fade',
    },
  },
  {
    id: 'dark-slate',
    name: 'Slate',
    category: 'dark',
    description: 'Cool slate tones',
    isCustom: false,
    header: {
      backgroundColor: '#1e293b',
      textColor: '#f1f5f9',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'uppercase',
      borderBottom: '1px solid #334155',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: '#0f172a',
      alternateRowColor: '#1e293b',
      textColor: '#cbd5e1',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#334155',
      radius: '8px',
      cellBorders: false,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#334155',
      shadow: 'lg',
      animation: 'fade',
    },
  },
  {
    id: 'dark-terminal',
    name: 'Terminal',
    category: 'dark',
    description: 'Hacker terminal style',
    isCustom: false,
    header: {
      backgroundColor: '#000000',
      textColor: '#00ff00',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'uppercase',
      borderBottom: '1px solid #00ff00',
      padding: '10px 14px',
    },
    body: {
      backgroundColor: '#000000',
      alternateRowColor: '#0a0a0a',
      textColor: '#00ff00',
      fontSize: 'sm',
      padding: '8px 14px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#00ff00',
      radius: '0',
      cellBorders: true,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#003300',
      shadow: 'none',
      animation: 'none',
    },
  },
  {
    id: 'dark-matrix',
    name: 'Matrix',
    category: 'dark',
    description: 'Green on black matrix',
    isCustom: false,
    header: {
      backgroundColor: '#022c22',
      textColor: '#4ade80',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '2px solid #22c55e',
      padding: '12px 16px',
    },
    body: {
      backgroundColor: '#052e16',
      alternateRowColor: '#14532d',
      textColor: '#86efac',
      fontSize: 'sm',
      padding: '10px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#22c55e',
      radius: '0',
      cellBorders: true,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#166534',
      shadow: 'md',
      animation: 'fade',
    },
  },
  {
    id: 'dark-nord',
    name: 'Nord',
    category: 'dark',
    description: 'Arctic inspired palette',
    isCustom: false,
    header: {
      backgroundColor: '#3b4252',
      textColor: '#eceff4',
      fontWeight: 'semibold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: '1px solid #4c566a',
      padding: '14px 16px',
    },
    body: {
      backgroundColor: '#2e3440',
      alternateRowColor: '#3b4252',
      textColor: '#d8dee9',
      fontSize: 'sm',
      padding: '12px 16px',
    },
    border: {
      style: 'solid',
      width: '1px',
      color: '#4c566a',
      radius: '6px',
      cellBorders: false,
      headerBorder: true,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#434c5e',
      shadow: 'sm',
      animation: 'fade',
    },
  },

  // GRADIENT STYLES (47-50)
  {
    id: 'gradient-purple',
    name: 'Purple Gradient',
    category: 'gradient',
    description: 'Purple to pink gradient header',
    isCustom: false,
    header: {
      backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      textColor: '#ffffff',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '16px 20px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#f5f3ff',
      textColor: '#4c1d95',
      fontSize: 'sm',
      padding: '14px 20px',
    },
    border: {
      style: 'none',
      width: '0',
      color: 'transparent',
      radius: '16px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#ede9fe',
      shadow: 'xl',
      animation: 'scale',
    },
  },
  {
    id: 'gradient-ocean',
    name: 'Ocean Gradient',
    category: 'gradient',
    description: 'Blue to teal gradient',
    isCustom: false,
    header: {
      backgroundColor: 'linear-gradient(135deg, #0093E9 0%, #80D0C7 100%)',
      textColor: '#ffffff',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '16px 20px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#ecfeff',
      textColor: '#164e63',
      fontSize: 'sm',
      padding: '14px 20px',
    },
    border: {
      style: 'none',
      width: '0',
      color: 'transparent',
      radius: '16px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#cffafe',
      shadow: 'xl',
      animation: 'scale',
    },
  },
  {
    id: 'gradient-sunset',
    name: 'Sunset Gradient',
    category: 'gradient',
    description: 'Orange to red gradient',
    isCustom: false,
    header: {
      backgroundColor: 'linear-gradient(135deg, #fa8231 0%, #eb3349 100%)',
      textColor: '#ffffff',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '16px 20px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#fff7ed',
      textColor: '#7c2d12',
      fontSize: 'sm',
      padding: '14px 20px',
    },
    border: {
      style: 'none',
      width: '0',
      color: 'transparent',
      radius: '16px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#ffedd5',
      shadow: 'xl',
      animation: 'scale',
    },
  },
  {
    id: 'gradient-forest',
    name: 'Forest Gradient',
    category: 'gradient',
    description: 'Green gradient header',
    isCustom: false,
    header: {
      backgroundColor: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
      textColor: '#ffffff',
      fontWeight: 'bold',
      fontSize: 'sm',
      textTransform: 'none',
      borderBottom: 'none',
      padding: '16px 20px',
    },
    body: {
      backgroundColor: '#ffffff',
      alternateRowColor: '#ecfdf5',
      textColor: '#064e3b',
      fontSize: 'sm',
      padding: '14px 20px',
    },
    border: {
      style: 'none',
      width: '0',
      color: 'transparent',
      radius: '16px',
      cellBorders: false,
      headerBorder: false,
    },
    effects: {
      striped: true,
      hoverable: true,
      hoverColor: '#d1fae5',
      shadow: 'xl',
      animation: 'scale',
    },
  },
];

// Store State Interface
interface TableStylesState {
  styles: TableStyleConfig[];
  activeStyleId: string;
  customStyles: TableStyleConfig[];

  // Actions
  setActiveStyle: (styleId: string) => void;
  getActiveStyle: () => TableStyleConfig | undefined;
  addCustomStyle: (style: Omit<TableStyleConfig, 'id' | 'isCustom'>) => string;
  updateCustomStyle: (id: string, updates: Partial<TableStyleConfig>) => void;
  deleteCustomStyle: (id: string) => void;
  duplicateStyle: (id: string) => string;
  getAllStyles: () => TableStyleConfig[];
  getStylesByCategory: (category: TableStyleCategory) => TableStyleConfig[];
}

export const useTableStylesStore = create<TableStylesState>()(
  persist(
    (set, get) => ({
      styles: defaultTableStyles,
      activeStyleId: 'theme-default',
      customStyles: [],

      setActiveStyle: (styleId) => {
        set({ activeStyleId: styleId });
      },

      getActiveStyle: () => {
        const state = get();
        return state.styles.find(s => s.id === state.activeStyleId)
          || state.customStyles.find(s => s.id === state.activeStyleId)
          || state.styles[0];
      },

      addCustomStyle: (style) => {
        const id = `custom-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
        const newStyle: TableStyleConfig = {
          ...style,
          id,
          isCustom: true,
          category: 'custom',
        };
        set((state) => ({
          customStyles: [...state.customStyles, newStyle],
        }));
        return id;
      },

      updateCustomStyle: (id, updates) => {
        set((state) => ({
          customStyles: state.customStyles.map((s) =>
            s.id === id ? { ...s, ...updates } : s
          ),
        }));
      },

      deleteCustomStyle: (id) => {
        set((state) => ({
          customStyles: state.customStyles.filter((s) => s.id !== id),
          activeStyleId: state.activeStyleId === id ? 'theme-default' : state.activeStyleId,
        }));
      },

      duplicateStyle: (id) => {
        const state = get();
        const original = state.styles.find(s => s.id === id) || state.customStyles.find(s => s.id === id);
        if (!original) return '';

        const newId = `custom-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
        const duplicated: TableStyleConfig = {
          ...original,
          id: newId,
          name: `${original.name} (Copy)`,
          isCustom: true,
          category: 'custom',
        };
        set((state) => ({
          customStyles: [...state.customStyles, duplicated],
        }));
        return newId;
      },

      getAllStyles: () => {
        const state = get();
        return [...state.styles, ...state.customStyles];
      },

      getStylesByCategory: (category) => {
        const state = get();
        const allStyles = [...state.styles, ...state.customStyles];
        return allStyles.filter(s => s.category === category);
      },
    }),
    {
      name: 'rustpress-table-styles',
    }
  )
);

// Category info for UI
export const tableStyleCategories: { id: TableStyleCategory; name: string; description: string }[] = [
  { id: 'theme', name: 'Theme Default', description: 'Uses your current theme colors' },
  { id: 'minimal', name: 'Minimal', description: 'Clean and simple designs' },
  { id: 'modern', name: 'Modern', description: 'Contemporary and trendy styles' },
  { id: 'classic', name: 'Classic', description: 'Traditional and timeless' },
  { id: 'colorful', name: 'Colorful', description: 'Vibrant and eye-catching' },
  { id: 'professional', name: 'Professional', description: 'Business and corporate' },
  { id: 'dark', name: 'Dark', description: 'Dark mode optimized' },
  { id: 'gradient', name: 'Gradient', description: 'Beautiful gradient headers' },
  { id: 'custom', name: 'Custom', description: 'Your custom styles' },
];
